//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePDFGenerator.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_DETAILS
    {
        public Nullable<int> InvoiceNum { get; set; }
        public Nullable<int> InvoiceLine { get; set; }
        public string Company { get; set; }
        public string PartNum { get; set; }
        public string LineDesc { get; set; }
        public string LineDescAr { get; set; }
        public Nullable<double> TotalMiscChrg { get; set; }
        public Nullable<double> PackNum { get; set; }
        public string PackNumAr { get; set; }
        public Nullable<double> PackLine { get; set; }
        public Nullable<double> OrderNum { get; set; }
        public Nullable<double> OrderLine { get; set; }
        public string CustID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string ShipViaCode { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string UnitPriceAr { get; set; }
        public string SalesUM { get; set; }
        public Nullable<double> SellingShipQty { get; set; }
        public string SellingShipQtyAr { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string TotalAr { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public string ProdNameAr { get; set; }
        public long Id { get; set; }
    }
}
