//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePDFGenerator.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AR_HEADER
    {
        public Nullable<int> InvoiceNum { get; set; }
        public string InvoiceNumAr { get; set; }
        public string Company { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public string OrderNumAr { get; set; }
        public string PONum { get; set; }
        public string PONumAr { get; set; }
        public string FOB { get; set; }
        public string TermsCode { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceAmt { get; set; }
        public string InvoiceAmtAr { get; set; }
        public string CurrencyCode { get; set; }
        public string Character01 { get; set; }
        public string Character02 { get; set; }
        public Nullable<double> Number01 { get; set; }
        public Nullable<double> Number02 { get; set; }
        public string Date01 { get; set; }
        public string Date02 { get; set; }
        public string CheckBox01 { get; set; }
        public string CheckBox02 { get; set; }
        public string ShortChar01 { get; set; }
        public string ShortChar02 { get; set; }
        public string CustID { get; set; }
        public string CustIDAr { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string TIN { get; set; }
        public string TINAr { get; set; }
        public string NameinArabic { get; set; }
        public string BilltoInArabic { get; set; }
        public string ShiptoinArabic { get; set; }
        public string TotalWords { get; set; }
        public string TotalWordsAr { get; set; }
        public string CurrencyCodeAr { get; set; }
        public long Id { get; set; }
    }
}
