//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoicePDFGenerator.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inv_TestingEntities : DbContext
    {
        public Inv_TestingEntities()
            : base("name=Inv_TestingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AR_DETAILS> AR_DETAILS { get; set; }
        public virtual DbSet<AR_DETAILS_befor_deleted> AR_DETAILS_befor_deleted { get; set; }
        public virtual DbSet<AR_HEADER> AR_HEADER { get; set; }
        public virtual DbSet<AR_HEADER_befor_deleted> AR_HEADER_befor_deleted { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<login_bk> login_bk { get; set; }
    }
}
